# Generated by Django 5.2.11 on 2026-02-11 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='asset.assettype'),
        ),
        migrations.AddField(
            model_name='risk',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='asset.businessunit'),
        ),
        migrations.AddField(
            model_name='risk',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='asset.costcenter'),
        ),
        migrations.AddField(
            model_name='risk',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='asset.section'),
        ),
    ]
