# Generated by Django 5.2.11 on 2026-02-11 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0008_riskexception_riskissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('risk_register', 'Risk Register')], default='risk_register', max_length=64)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=32)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hour', models.PositiveSmallIntegerField(default=9)),
                ('minute', models.PositiveSmallIntegerField(default=0)),
                ('recipients', models.TextField(blank=True, help_text='Comma-separated emails or usernames.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='risknotification',
            name='notification_type',
            field=models.CharField(choices=[('approval_requested', 'Approval Requested'), ('approval_decided', 'Approval Decided'), ('report_ready', 'Report Ready')], max_length=64),
        ),
        migrations.AlterField(
            model_name='risknotification',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='risk.risk'),
        ),
        migrations.CreateModel(
            name='RiskReportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='success', max_length=32)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='risk.riskreportschedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
