# Generated by Codex on 2026-02-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0009_riskreportschedule_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category_type",
                    models.CharField(choices=[("risk", "Risk"), ("control", "Control")], max_length=32),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="riskcategory",
            constraint=models.UniqueConstraint(
                fields=("category_type", "name"), name="uq_risk_category_type_name"
            ),
        ),
    ]

