# Generated by Codex on 2026-02-12

from django.db import migrations, models
import django.db.models.deletion
from django.core.validators import MaxValueValidator, MinValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0010_riskcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThirdPartyVendor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=128)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("owner", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(choices=[("active", "Active"), ("inactive", "Inactive")], default="active", max_length=32)),
                ("criticality", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")], default="medium", max_length=32)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ThirdPartyRisk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("open", "Open"), ("in_progress", "In Progress"), ("closed", "Closed")], default="open", max_length=32)),
                ("owner", models.CharField(blank=True, max_length=255)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("likelihood", models.PositiveSmallIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(5)])),
                ("impact", models.PositiveSmallIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(5)])),
                ("inherent_score", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("residual_score", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("vendor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="risks", to="risk.thirdpartyvendor")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]

