# Generated by Codex on 2026-02-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0011_third_party_vendor_risk"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyStandard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("category", models.CharField(blank=True, max_length=128)),
                ("owner", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("retired", "Retired")], default="draft", max_length=32)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("review_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PolicyControlMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("control", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="policy_mappings", to="risk.riskcontrol")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="control_mappings", to="risk.policystandard")),
            ],
        ),
        migrations.CreateModel(
            name="PolicyRiskMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="risk_mappings", to="risk.policystandard")),
                ("risk", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="policy_mappings", to="risk.risk")),
            ],
        ),
        migrations.AddConstraint(
            model_name="policycontrolmapping",
            constraint=models.UniqueConstraint(fields=("policy", "control"), name="uq_policy_control_mapping"),
        ),
        migrations.AddConstraint(
            model_name="policyriskmapping",
            constraint=models.UniqueConstraint(fields=("policy", "risk"), name="uq_policy_risk_mapping"),
        ),
    ]

