# Generated by Codex on 2026-02-12

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0012_policy_standard_and_mappings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlTestPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("owner", models.CharField(blank=True, max_length=255)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("quarterly", "Quarterly"), ("semi_annual", "Semi-Annual"), ("annual", "Annual")],
                        default="annual",
                        max_length=32,
                    ),
                ),
                ("next_due_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_plans",
                        to="risk.riskcontrol",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ControlTestRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tested_at", models.DateField()),
                ("tester", models.CharField(blank=True, max_length=255)),
                (
                    "result",
                    models.CharField(
                        choices=[("pass", "Pass"), ("fail", "Fail"), ("inconclusive", "Inconclusive")],
                        max_length=32,
                    ),
                ),
                (
                    "effectiveness_score",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="risk.controltestplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-tested_at"],
            },
        ),
    ]
