# Generated by Codex on 2026-02-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0013_control_test_plan_run"),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernanceProgram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("owner", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("retired", "Retired")], default="draft", max_length=32)),
                ("objective", models.TextField(blank=True)),
                ("review_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("assessment_type", models.CharField(choices=[("internal", "Internal"), ("external", "External")], default="internal", max_length=32)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("in_progress", "In Progress"), ("complete", "Complete")], default="draft", max_length=32)),
                ("owner", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("scope", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceFramework",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("owner", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("retired", "Retired")], default="draft", max_length=32)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceRequirement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("compliant", "Compliant"), ("partial", "Partially Compliant"), ("noncompliant", "Non-Compliant"), ("not_applicable", "Not Applicable"), ("unknown", "Unknown")], default="unknown", max_length=32)),
                ("evidence", models.TextField(blank=True)),
                ("last_reviewed", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("control", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="compliance_requirements", to="risk.riskcontrol")),
                ("framework", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="requirements", to="risk.complianceframework")),
            ],
            options={
                "ordering": ["framework__name", "code"],
            },
        ),
        migrations.CreateModel(
            name="Vulnerability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("severity", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], default="medium", max_length=32)),
                ("status", models.CharField(choices=[("open", "Open"), ("mitigated", "Mitigated"), ("accepted", "Accepted"), ("closed", "Closed")], default="open", max_length=32)),
                ("owner", models.CharField(blank=True, max_length=255)),
                ("discovered_at", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="vulnerabilities", to="asset.asset")),
                ("risk", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="vulnerabilities", to="risk.risk")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="compliancerequirement",
            constraint=models.UniqueConstraint(fields=("framework", "code"), name="uq_compliance_requirement_code"),
        ),
    ]
