# Generated by Django 5.2.11 on 2026-02-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0015_risksource'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='event_description',
            field=models.TextField(blank=True, verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='risk',
            name='impact_description',
            field=models.TextField(blank=True, verbose_name='Impact'),
        ),
    ]
