# Generated by Django 5.2.11 on 2026-02-13 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0016_risk_event_description_risk_impact_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='event_description',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='impact_description',
        ),
    ]
