# Generated by Django 5.2.11 on 2026-02-13 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_asset_geo_zone_asset_infrastructure_criticality_and_more'),
        ('risk', '0017_remove_risk_event_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('hazard_type', models.CharField(choices=[('natural', 'Natural'), ('industrial', 'Industrial'), ('utility', 'Utility'), ('cyber', 'Cyber')], default='utility', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('default_likelihood', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='risk',
            name='dynamic_risk_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='risk',
            name='critical_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='risk.criticalservice'),
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration_hours', models.PositiveIntegerField(default=4)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='risk.hazard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBIAProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mao_hours', models.PositiveIntegerField(default=24)),
                ('rto_hours', models.PositiveIntegerField(default=8)),
                ('rpo_hours', models.PositiveIntegerField(default=4)),
                ('notes', models.TextField(blank=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bia_profile', to='risk.criticalservice')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='risk.criticalservice')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAssetMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('support', 'Support')], default='support', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_mappings', to='asset.asset')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_mappings', to='risk.criticalservice')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_mappings', to='risk.serviceprocess')),
            ],
        ),
        migrations.CreateModel(
            name='HazardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hazard_links', to='asset.asset')),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='risk.hazard')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hazard_links', to='risk.criticalservice')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('asset__isnull', False), ('service__isnull', False), _connector='OR'), name='ck_hazard_link_target')],
            },
        ),
        migrations.CreateModel(
            name='ImpactEscalationCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_category', models.CharField(choices=[('financial', 'Financial'), ('operational', 'Operational'), ('legal', 'Legal'), ('reputational', 'Reputational'), ('environmental', 'Environmental'), ('human_safety', 'Human Safety')], max_length=32)),
                ('t1_hours', models.PositiveIntegerField(default=1)),
                ('t1_label', models.CharField(max_length=255)),
                ('t2_hours', models.PositiveIntegerField(default=4)),
                ('t2_label', models.CharField(max_length=255)),
                ('t3_hours', models.PositiveIntegerField(default=8)),
                ('t3_label', models.CharField(max_length=255)),
                ('t4_hours', models.PositiveIntegerField(default=24)),
                ('t4_label', models.CharField(max_length=255)),
                ('t5_hours', models.PositiveIntegerField(default=72)),
                ('t5_label', models.CharField(max_length=255)),
                ('bia_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_curves', to='risk.servicebiaprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bia_profile', 'impact_category'), name='uq_bia_category')],
            },
        ),
        migrations.AddConstraint(
            model_name='serviceprocess',
            constraint=models.UniqueConstraint(fields=('service', 'code'), name='uq_service_process_code'),
        ),
        migrations.AddConstraint(
            model_name='serviceassetmapping',
            constraint=models.UniqueConstraint(fields=('service', 'process', 'asset'), name='uq_service_process_asset'),
        ),
    ]
