# Generated by Django 5.2.11 on 2026-02-16 06:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0024_continuity_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controltestplan',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='risk.riskcontrol', verbose_name='Control'),
        ),
        migrations.AlterField(
            model_name='controltestplan',
            name='frequency',
            field=models.CharField(choices=[('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], default='annual', max_length=32, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='controltestplan',
            name='next_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next due date'),
        ),
        migrations.AlterField(
            model_name='controltestplan',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='controltestplan',
            name='owner',
            field=models.CharField(blank=True, max_length=255, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='controltestrun',
            name='effectiveness_score',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Effectiveness score'),
        ),
        migrations.AlterField(
            model_name='controltestrun',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='controltestrun',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='risk.controltestplan', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='controltestrun',
            name='result',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('inconclusive', 'Inconclusive')], max_length=32, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='controltestrun',
            name='tested_at',
            field=models.DateField(verbose_name='Tested at'),
        ),
        migrations.AlterField(
            model_name='controltestrun',
            name='tester',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tester'),
        ),
    ]
