# Generated by Django 5.2.11 on 2026-02-16 08:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0025_alter_controltestplan_control_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicebiaprofile",
            name="crisis_trigger_rules",
            field=models.JSONField(blank=True, null=True, verbose_name="Crisis trigger rules"),
        ),
        migrations.AddField(
            model_name="servicebiaprofile",
            name="impact_environmental",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Environmental impact",
            ),
        ),
        migrations.AddField(
            model_name="servicebiaprofile",
            name="impact_escalation_curve",
            field=models.JSONField(blank=True, null=True, verbose_name="Impact escalation curve"),
        ),
        migrations.AddField(
            model_name="servicebiaprofile",
            name="impact_financial",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Financial impact",
            ),
        ),
        migrations.AddField(
            model_name="servicebiaprofile",
            name="impact_legal",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Legal impact",
            ),
        ),
        migrations.AddField(
            model_name="servicebiaprofile",
            name="impact_operational",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Operational impact",
            ),
        ),
        migrations.AddField(
            model_name="servicebiaprofile",
            name="impact_reputation",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Reputation impact",
            ),
        ),
        migrations.AddField(
            model_name="servicebiaprofile",
            name="impact_safety",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Safety impact",
            ),
        ),
        migrations.AddField(
            model_name="servicebiaprofile",
            name="service_criticality",
            field=models.CharField(
                choices=[
                    ("LIFE_CRITICAL", "Life critical"),
                    ("ENVIRONMENT_CRITICAL", "Environment critical"),
                    ("INFRASTRUCTURE_CRITICAL", "Infrastructure critical"),
                    ("BUSINESS_CRITICAL", "Business critical"),
                    ("SUPPORT_SERVICE", "Support service"),
                ],
                default="SUPPORT_SERVICE",
                max_length=32,
                verbose_name="Service criticality",
            ),
        ),
        migrations.AlterField(
            model_name="complianceframework",
            name="code",
            field=models.CharField(max_length=64, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="complianceframework",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="complianceframework",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="complianceframework",
            name="owner",
            field=models.CharField(blank=True, max_length=255, verbose_name="Owner"),
        ),
        migrations.AlterField(
            model_name="complianceframework",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("active", "Active"), ("retired", "Retired")],
                default="draft",
                max_length=32,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="compliancerequirement",
            name="code",
            field=models.CharField(max_length=64, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="compliancerequirement",
            name="control",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compliance_requirements",
                to="risk.riskcontrol",
                verbose_name="Control",
            ),
        ),
        migrations.AlterField(
            model_name="compliancerequirement",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="compliancerequirement",
            name="evidence",
            field=models.TextField(blank=True, verbose_name="Evidence"),
        ),
        migrations.AlterField(
            model_name="compliancerequirement",
            name="framework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="risk.complianceframework",
                verbose_name="Framework",
            ),
        ),
        migrations.AlterField(
            model_name="compliancerequirement",
            name="last_reviewed",
            field=models.DateField(blank=True, null=True, verbose_name="Last reviewed"),
        ),
        migrations.AlterField(
            model_name="compliancerequirement",
            name="status",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("partial", "Partially Compliant"),
                    ("noncompliant", "Non-Compliant"),
                    ("not_applicable", "Not Applicable"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=32,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="compliancerequirement",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="governanceprogram",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="governanceprogram",
            name="objective",
            field=models.TextField(blank=True, verbose_name="Objective"),
        ),
        migrations.AlterField(
            model_name="governanceprogram",
            name="owner",
            field=models.CharField(blank=True, max_length=255, verbose_name="Owner"),
        ),
        migrations.AlterField(
            model_name="governanceprogram",
            name="review_date",
            field=models.DateField(blank=True, null=True, verbose_name="Review date"),
        ),
        migrations.AlterField(
            model_name="governanceprogram",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("active", "Active"), ("retired", "Retired")],
                default="draft",
                max_length=32,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="policycontrolmapping",
            name="control",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policy_mappings",
                to="risk.riskcontrol",
                verbose_name="Control",
            ),
        ),
        migrations.AlterField(
            model_name="policycontrolmapping",
            name="notes",
            field=models.CharField(blank=True, max_length=255, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="policycontrolmapping",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="control_mappings",
                to="risk.policystandard",
                verbose_name="Policy",
            ),
        ),
        migrations.AlterField(
            model_name="policyriskmapping",
            name="notes",
            field=models.CharField(blank=True, max_length=255, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="policyriskmapping",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_mappings",
                to="risk.policystandard",
                verbose_name="Policy",
            ),
        ),
        migrations.AlterField(
            model_name="policyriskmapping",
            name="risk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policy_mappings",
                to="risk.risk",
                verbose_name="Risk",
            ),
        ),
        migrations.AlterField(
            model_name="policystandard",
            name="category",
            field=models.CharField(blank=True, max_length=128, verbose_name="Category"),
        ),
        migrations.AlterField(
            model_name="policystandard",
            name="code",
            field=models.CharField(max_length=64, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="policystandard",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="policystandard",
            name="effective_date",
            field=models.DateField(blank=True, null=True, verbose_name="Effective date"),
        ),
        migrations.AlterField(
            model_name="policystandard",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="policystandard",
            name="owner",
            field=models.CharField(blank=True, max_length=255, verbose_name="Owner"),
        ),
        migrations.AlterField(
            model_name="policystandard",
            name="review_date",
            field=models.DateField(blank=True, null=True, verbose_name="Review date"),
        ),
        migrations.AlterField(
            model_name="policystandard",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("active", "Active"), ("retired", "Retired")],
                default="draft",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
