# Generated by Codex on 2026-02-12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetAccessTeam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("notes", models.TextField(blank=True)),
                ("members", models.ManyToManyField(blank=True, related_name="asset_access_teams", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="access_teams",
            field=models.ManyToManyField(blank=True, related_name="assets", to="asset.assetaccessteam"),
        ),
        migrations.AddField(
            model_name="asset",
            name="access_users",
            field=models.ManyToManyField(blank=True, related_name="asset_access", to=settings.AUTH_USER_MODEL),
        ),
    ]
