# Generated by Django 5.2.11 on 2026-02-13 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_asset_access_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='geo_zone',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='asset',
            name='infrastructure_criticality',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='asset',
            name='seismic_risk_coefficient',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
