# Generated by Django 5.2.11 on 2026-02-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsyncrun',
            name='plugin_name',
            field=models.CharField(default='excel_bootstrap', max_length=64),
        ),
        migrations.AddField(
            model_name='integrationsyncrun',
            name='plugin_version',
            field=models.CharField(default='v1', max_length=16),
        ),
    ]
